name: Controlling the Execution Flow

on:
    workflow_dispatch:
      inputs:
        pass-unit-tests:
          description: 'Indica si las pruebas unitarias deben pasar para continuar'
          type: boolean
          default: false
          required: true
jobs:
    lint-build:
        runs-on: ubuntu-latest
        steps:
        - run: echo "Linting and building project"
    unit-tests:
        runs-on: ubuntu-latest
        steps:
        - name: Running unit tests
          run: echo "Running tests..."
          if: ${{github.event.inputs.pass-unit-tests == false}}
        - name: Failing tests
          run: echo "Failing tests..."
    deploy-nonprod:
        runs-on: ubuntu-latest
        needs: [lint-build, unit-tests] 
        steps:
            - name : Deploying to nonprod
              run: echo "Deploying to nonprod..."
    e2e-tests:
        runs-on: ubuntu-latest
        needs: deploy-nonprod
        steps:
            - name : Running E2E tests
              run: echo "Running E2E tests..."
    load-tests:
        runs-on: ubuntu-latest
        needs: deploy-nonprod
        steps:
            - name : Running load tests
              run: echo "Running load tests..."
    deploy-prod:
        runs-on: ubuntu-latest
        needs: [e2e-tests, load-tests] 
        steps:
            - name : Deploying to prod
              run: echo "Deploying to prod..."

